/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AppRootRouteImport } from './routes/_appRoot'
import { Route as AppRootIndexRouteImport } from './routes/_appRoot.index'
import { Route as ShareGistIdRouteImport } from './routes/share.$gistId'
import { Route as AppRootSettingsRouteImport } from './routes/_appRoot.settings'
import { Route as AppRootFileRouteImport } from './routes/_appRoot.file'
import { Route as AppRootTagsIndexRouteImport } from './routes/_appRoot.tags.index'
import { Route as AppRootNotesIndexRouteImport } from './routes/_appRoot.notes.index'
import { Route as AppRootFeedsIndexRouteImport } from './routes/_appRoot.feeds.index'
import { Route as AppRootDocsIndexRouteImport } from './routes/_appRoot.docs.index'
import { Route as AppRootTagsSplatRouteImport } from './routes/_appRoot.tags_.$'
import { Route as AppRootNotesSplatRouteImport } from './routes/_appRoot.notes_.$'
import { Route as AppRootFeedsSplatRouteImport } from './routes/_appRoot.feeds_.$'
import { Route as AppRootDocsDocRouteImport } from './routes/_appRoot.docs_.$doc'

const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRootRoute = AppRootRouteImport.update({
  id: '/_appRoot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRootIndexRoute = AppRootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRootRoute,
} as any)
const ShareGistIdRoute = ShareGistIdRouteImport.update({
  id: '/share/$gistId',
  path: '/share/$gistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRootSettingsRoute = AppRootSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootFileRoute = AppRootFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootTagsIndexRoute = AppRootTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootNotesIndexRoute = AppRootNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootFeedsIndexRoute = AppRootFeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootDocsIndexRoute = AppRootDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootTagsSplatRoute = AppRootTagsSplatRouteImport.update({
  id: '/tags_/$',
  path: '/tags/$',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootNotesSplatRoute = AppRootNotesSplatRouteImport.update({
  id: '/notes_/$',
  path: '/notes/$',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootFeedsSplatRoute = AppRootFeedsSplatRouteImport.update({
  id: '/feeds_/$',
  path: '/feeds/$',
  getParentRoute: () => AppRootRoute,
} as any)
const AppRootDocsDocRoute = AppRootDocsDocRouteImport.update({
  id: '/docs_/$doc',
  path: '/docs/$doc',
  getParentRoute: () => AppRootRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRootIndexRoute
  '/ai': typeof AiRoute
  '/file': typeof AppRootFileRoute
  '/settings': typeof AppRootSettingsRoute
  '/share/$gistId': typeof ShareGistIdRoute
  '/docs/$doc': typeof AppRootDocsDocRoute
  '/feeds/$': typeof AppRootFeedsSplatRoute
  '/notes/$': typeof AppRootNotesSplatRoute
  '/tags/$': typeof AppRootTagsSplatRoute
  '/docs/': typeof AppRootDocsIndexRoute
  '/feeds/': typeof AppRootFeedsIndexRoute
  '/notes/': typeof AppRootNotesIndexRoute
  '/tags/': typeof AppRootTagsIndexRoute
}
export interface FileRoutesByTo {
  '/ai': typeof AiRoute
  '/file': typeof AppRootFileRoute
  '/settings': typeof AppRootSettingsRoute
  '/share/$gistId': typeof ShareGistIdRoute
  '/': typeof AppRootIndexRoute
  '/docs/$doc': typeof AppRootDocsDocRoute
  '/feeds/$': typeof AppRootFeedsSplatRoute
  '/notes/$': typeof AppRootNotesSplatRoute
  '/tags/$': typeof AppRootTagsSplatRoute
  '/docs': typeof AppRootDocsIndexRoute
  '/feeds': typeof AppRootFeedsIndexRoute
  '/notes': typeof AppRootNotesIndexRoute
  '/tags': typeof AppRootTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_appRoot': typeof AppRootRouteWithChildren
  '/ai': typeof AiRoute
  '/_appRoot/file': typeof AppRootFileRoute
  '/_appRoot/settings': typeof AppRootSettingsRoute
  '/share/$gistId': typeof ShareGistIdRoute
  '/_appRoot/': typeof AppRootIndexRoute
  '/_appRoot/docs_/$doc': typeof AppRootDocsDocRoute
  '/_appRoot/feeds_/$': typeof AppRootFeedsSplatRoute
  '/_appRoot/notes_/$': typeof AppRootNotesSplatRoute
  '/_appRoot/tags_/$': typeof AppRootTagsSplatRoute
  '/_appRoot/docs/': typeof AppRootDocsIndexRoute
  '/_appRoot/feeds/': typeof AppRootFeedsIndexRoute
  '/_appRoot/notes/': typeof AppRootNotesIndexRoute
  '/_appRoot/tags/': typeof AppRootTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/file'
    | '/settings'
    | '/share/$gistId'
    | '/docs/$doc'
    | '/feeds/$'
    | '/notes/$'
    | '/tags/$'
    | '/docs/'
    | '/feeds/'
    | '/notes/'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai'
    | '/file'
    | '/settings'
    | '/share/$gistId'
    | '/'
    | '/docs/$doc'
    | '/feeds/$'
    | '/notes/$'
    | '/tags/$'
    | '/docs'
    | '/feeds'
    | '/notes'
    | '/tags'
  id:
    | '__root__'
    | '/_appRoot'
    | '/ai'
    | '/_appRoot/file'
    | '/_appRoot/settings'
    | '/share/$gistId'
    | '/_appRoot/'
    | '/_appRoot/docs_/$doc'
    | '/_appRoot/feeds_/$'
    | '/_appRoot/notes_/$'
    | '/_appRoot/tags_/$'
    | '/_appRoot/docs/'
    | '/_appRoot/feeds/'
    | '/_appRoot/notes/'
    | '/_appRoot/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRootRoute: typeof AppRootRouteWithChildren
  AiRoute: typeof AiRoute
  ShareGistIdRoute: typeof ShareGistIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appRoot': {
      id: '/_appRoot'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appRoot/': {
      id: '/_appRoot/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppRootIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/share/$gistId': {
      id: '/share/$gistId'
      path: '/share/$gistId'
      fullPath: '/share/$gistId'
      preLoaderRoute: typeof ShareGistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appRoot/settings': {
      id: '/_appRoot/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppRootSettingsRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/file': {
      id: '/_appRoot/file'
      path: '/file'
      fullPath: '/file'
      preLoaderRoute: typeof AppRootFileRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/tags/': {
      id: '/_appRoot/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AppRootTagsIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/notes/': {
      id: '/_appRoot/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AppRootNotesIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/feeds/': {
      id: '/_appRoot/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof AppRootFeedsIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/docs/': {
      id: '/_appRoot/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof AppRootDocsIndexRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/tags_/$': {
      id: '/_appRoot/tags_/$'
      path: '/tags/$'
      fullPath: '/tags/$'
      preLoaderRoute: typeof AppRootTagsSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/notes_/$': {
      id: '/_appRoot/notes_/$'
      path: '/notes/$'
      fullPath: '/notes/$'
      preLoaderRoute: typeof AppRootNotesSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/feeds_/$': {
      id: '/_appRoot/feeds_/$'
      path: '/feeds/$'
      fullPath: '/feeds/$'
      preLoaderRoute: typeof AppRootFeedsSplatRouteImport
      parentRoute: typeof AppRootRoute
    }
    '/_appRoot/docs_/$doc': {
      id: '/_appRoot/docs_/$doc'
      path: '/docs/$doc'
      fullPath: '/docs/$doc'
      preLoaderRoute: typeof AppRootDocsDocRouteImport
      parentRoute: typeof AppRootRoute
    }
  }
}

interface AppRootRouteChildren {
  AppRootFileRoute: typeof AppRootFileRoute
  AppRootSettingsRoute: typeof AppRootSettingsRoute
  AppRootIndexRoute: typeof AppRootIndexRoute
  AppRootDocsDocRoute: typeof AppRootDocsDocRoute
  AppRootFeedsSplatRoute: typeof AppRootFeedsSplatRoute
  AppRootNotesSplatRoute: typeof AppRootNotesSplatRoute
  AppRootTagsSplatRoute: typeof AppRootTagsSplatRoute
  AppRootDocsIndexRoute: typeof AppRootDocsIndexRoute
  AppRootFeedsIndexRoute: typeof AppRootFeedsIndexRoute
  AppRootNotesIndexRoute: typeof AppRootNotesIndexRoute
  AppRootTagsIndexRoute: typeof AppRootTagsIndexRoute
}

const AppRootRouteChildren: AppRootRouteChildren = {
  AppRootFileRoute: AppRootFileRoute,
  AppRootSettingsRoute: AppRootSettingsRoute,
  AppRootIndexRoute: AppRootIndexRoute,
  AppRootDocsDocRoute: AppRootDocsDocRoute,
  AppRootFeedsSplatRoute: AppRootFeedsSplatRoute,
  AppRootNotesSplatRoute: AppRootNotesSplatRoute,
  AppRootTagsSplatRoute: AppRootTagsSplatRoute,
  AppRootDocsIndexRoute: AppRootDocsIndexRoute,
  AppRootFeedsIndexRoute: AppRootFeedsIndexRoute,
  AppRootNotesIndexRoute: AppRootNotesIndexRoute,
  AppRootTagsIndexRoute: AppRootTagsIndexRoute,
}

const AppRootRouteWithChildren =
  AppRootRoute._addFileChildren(AppRootRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRootRoute: AppRootRouteWithChildren,
  AiRoute: AiRoute,
  ShareGistIdRoute: ShareGistIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
